  
name: End-to-end tests
on: [push]
jobs:
  cypress-run:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Run backend
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          run: npm run start
      - name: tr
        run: echo hello
        
 
